steps:
  - name: "gcr.io/cloud-builders/curl"
    args:
      [
        "-X",
        "POST",
        "-H",
        "Content-type: application/json",
        "--data",
        '{"text":"`wt-tracker:$_TAG-$SHORT_SHA` build started!"}',
        "${_WEBHOOK_URL}",
      ]
  - name: "gcr.io/cloud-builders/docker"
    args:
      [
        "build",
        "-t",
        "eu.gcr.io/$PROJECT_ID/wt-tracker:$_TAG-$SHORT_SHA",
        ".",
      ]
  - name: "gcr.io/cloud-builders/curl"
    args:
      [
        "-X",
        "POST",
        "-H",
        "Content-type: application/json",
        "--data",
        '{"text":"`wt-tracker:$_TAG-$SHORT_SHA` build completed!"}',
        "${_WEBHOOK_URL}",
      ]
substitutions:
  _TAG: $TAG_NAME
images:
  - "eu.gcr.io/$PROJECT_ID/wt-tracker"
